name: Backup MyAnimeList Action
description: Github action to save your MyAnimeList in the repository
author: 'lucas8x'

branding:
  icon: 'archive'
  color: 'blue'

inputs:
  mal_username:
    description: 'Your MyAnimeList username'
    required: true
  mal_list_type:
    description: 'Which list you want to save'
    default: 'both'
  output_dir:
    description: 'Output directory'
    default: .
  anime_string_format:
    description: Anime string format on txt file
    default: '%t% - Ep %wep%/%tep%'
    # Result: Sailor Moon - Ep 46/46
  manga_string_format:
    description: Manga string format on txt file
    default: '%t% - Ch %cr%/%tc% - Vol %vr%/%tv%'
    # Result: Sailor Moon - Ch 61/61 - Vol 18/18
  hide_username:
    description: 'Hide your MyAnimeList username from logs and files'
    default: 'false'

runs:
  using: node20
  main: dist/index.js
